baseURL = 'https://MistbornOne.github.io'
languageCode = 'en-us'
title = 'Ian Watkins'
theme = 'main'
enableRobotsTXT = true
enableEmoji = true

[caches]
[caches.images]
dir = ':cacheDir/images'

[params]
description = "I'm the dad of 5 humans and 3 dogs who loves a good cup of coffee and an even better book. Follower of Jesus. Major Nerd. This is where I share what I am learning as I go."
author = "Ian Watkins"
github = "https://github.com/MistbornOne"
linkedin = "https://linkedin.com/in/ian-watkins-5000a712a/"
email = "iankwatkins@gmail.com"
avatar = "/images/ghibli.jpeg"
enableDarkMode = true
defaultTheme = "dark"                                                                                                                                                                       # or "light"
codeBlockCopyButton = true

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 20
[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 30


[markup]
[markup.highlight]
codeFences = true
guessSyntax = false
#hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "catppuccin-frappe"
tabWidth = 4
