baseURL = 'https://MistbornOne.github.io'
languageCode = 'en-us'
title = 'Ian Watkins'
theme = 'main'
enableRobotsTXT = true
enableEmoji = true

[params]
description = "My Personal Website and Blog for Sharing What I Learn as I Go"
author = "Ian Watkins"
github = "https://github.com/MistbornOne"
linkedin = "https://linkedin.com/in/ian-watkins-5000a712a/"
email = "iankwatkins@gmail.com"
avatar = "/images/ghibli.jpeg"
enableDarkMode = true
defaultTheme = "dark"                                                         # or "light"
codeBlockCopyButton = true

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 20
[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 30
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 40

[markup]
[markup.highlight]
codeFences = true
guessSyntax = false
#hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "catppuccin-frappe"
tabWidth = 4
